import Footer from "../../views/footer";
import {render, screen} from '@testing-library/react';

// Generated by Chat GPT to get rid of console warning for mocking
jest.mock('react-i18next', () => ({
  useTranslation: () => ({ t: key => key }),
}));

test('Render Footer', async () => {
  render(<Footer/>);
  await screen.findByText('SlugSwap');
})