import {Category, SubCategory, Attributes} from './schema';

export async function dbGetCategory(): Promise<Category[]> {
  const res = await fetch('http://localhost:3013/api/v0/category');
  // Line below generated by ChatGPT
  const categories = await res.json() as Category[];
  // console.log(categories);
  return categories;
}

export async function dbGetSubCategory(categoryid: string): Promise<SubCategory[]> {
  const res = await fetch('http://localhost:3013/api/v0/subcategory/'+categoryid);
  const subcategories = await res.json() as SubCategory[];
  return subcategories;
}

export async function dbGetAttribute(subcategoryid: string): Promise<Attributes> {
  const res = await fetch('http://localhost:3013/api/v0/attribute/'+subcategoryid);
  const attributes = await res.json() as Attributes;
  return attributes;
}